# Generated by Django 5.1.6 on 2025-05-21 23:25

import base.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pickup_location", base.fields.LocationField()),
                ("dropoff_location", base.fields.LocationField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Ride Requested"),
                            ("ACCEPTED", "Ride Accepted"),
                            ("STARTED", "Ride Started"),
                            ("COMPLETED", "Ride Completed"),
                            ("CANCELLED", "Ride Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Accounts.client",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Accounts.driver",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
